### ISSUE TITLE
so

### ISSUE THREAD

**Issue by izabera** [modernish/modernish#3] opened 2016-11-05 06:13 UTC
```
so () { return "$?"; }
```

**Comment by McDutchie** [comment] 2016-11-06 13:47
This works, but in a subtly different way: the exit status is not either 0 or 1, but can be anything from 0 to 255. Also it always involves executing both a function and a builtin, whereas the alias only does this on shells where `let` is not built in so needs to be implemented as a function.

Another thing is that the above function doesn't validate arguments (in this case, enforce zero arguments). My policy is to be very strict about that; this tends to catch bugs caused by unexpected field splitting and the like.

Come to think of it, though, my current alias doesn't validate arguments either; it accepts further expressions for `let`. Fixed in commit db926d58c460a9d30f6d6beb5475f71414e101fb by wrapping the alias definition in `{`…`; }`. 

Thanks for the report.

**Closed by McDutchie** 2016-11-06 13:47 UTC
